### ISSUE TITLE
locating article in dumps

### ISSUE THREAD

**Issue by ErikBorra** [halfak/Mediawiki-Utilities#31]
Hi,

to locate a specific article in the english pages-meta-history wikipedia dump, I iterate over all the dump files and iterate over all the pages in it. This is very time consuming. Do you know a more efficient way?

Thanks,

Erik

**Comment by halfak** [comment]
Yes.  You can use the Wikipedia API to get at a single page.  

E.g. http://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles=Anachronism&rvprop=content|ids|timestamp|comment&continue=

See http://en.wikipedia.org/w/api.php?action=help&modules=query%2Brevisions

**Comment by halfak** [comment]
I should mention that you can use this library to perform those queries too. 

    >>> from mw import api
    >>> session = api.Session("https://en.wikipedia.org/api.php")
    Sending requests with default User-Agent.  Set 'user_agent' on api.Session to quiet this message.
    >>> revisions = session.revisions.query(titles=['Anachronism'], properties=['ids', 'timestamp', 'content', 'comment'])

**Comment by ErikBorra** [comment]
Thanks Aaron,

I do need the full edit history for those articles though, so the API is of not much use :p Just wondering about the most efficient way to locate an article within the pages-meta-history dump.

Best,

Erik

**Comment by makoshark** [comment]
The API can trivally give you the full edit history for a given page. Am I missing something here?

**Comment by ErikBorra** [comment]
@makoshark you are right of course, sorry for not explaining myself better.

I have a couple of hundred big articles (10K+ edits) for which I need to retrieve and parse the full edit history. Downloading the full pages-meta-history dump once and processing that is faster than downloading the full revision history via the API. 

I am wondering whether it is possible to locate the articles in the dumps faster than just processing each (partial) dump and iterating over all the pages in them, whilst checking whether the page.title is the same as the article I am interested in.

Thanks for your suggestions.

Best,

Erik

**Comment by halfak** [comment]
The files names of the dumps suggest the page_ids contained. 

For example [enwiki-20150304-pages-meta-history1.xml-p000000010p000002944.7z](http://dumps.wikimedia.org/enwiki/20150304/enwiki-20150304-pages-meta-history1.xml-p000000010p000002944.7z) contains pages with page_id between 10 and 2944.

**Comment by ErikBorra** [comment]
That is useful information, thanks! 

Apart from those page_ids in the file names of the dumps, are there any possibilities to more quickly locate a specific article in a specific dump?

**Comment by makoshark** [comment]
One challenge, however, is that there is no random access within dumps within the 7z dumps. People have experimented with indexed compressed dumps using gzip and bzip2 that allow for something more like random access because they match individual articles not only to particular dumps files but to places within the dumps. Where I've seen this, it this method requires generating the index and recompressing the dumps. Otherwise, you're stuck matching titles to page ids and then finding the page id in the dumps.

In your case where you want hundreds of pages, it's likely that you're going to be going through and parsing most of the dumps anyway since there are only a couple hundred dump files...

If you increase the number of revisions fetched with each API call to the 500 revision max, I'm not convined that it would not be faster and easier to use the API. My experience is that even with 1000 pages with 10000 revisions each, you should have your dataset in under a day.

**Comment by ErikBorra** [comment]
These are useful considerations, thanks for the prompt responses!
